services:
  - type: web
    name: hr-software-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: FRONT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        sync: false
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_SENDER
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_BUCKETNAME
        sync: false
